config/routes.rb
Rails.application.routes.draw do
  root to: 'public#index'
  get '/private', to: 'private#index'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :check_if_user_is_logged_in

  helper_method :logged_in_and_valid_user?

  private
  def check_if_user_is_logged_in
    redirect_to login_path unless logged_in_and_valid_user?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in_and_valid_user?
    !!current_user
  end
end

app/controllers/private_controller.rb
class PrivateController < ApplicationController
  def index
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  skip_before_action :check_if_user_is_logged_in

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_if_user_is_logged_in, except: [:destroy]

  def new
  end

  def create
    @user = User.find_by(name: params[:name])
    if user_and_password_are_valid?
      session[:user_id] = @user.id
      redirect_to private_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def user_and_password_are_valid?
    @user && @user.authenticate(params[:password])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_if_user_is_logged_in

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to(private_path)
    else
      render(:new)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sessions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type="text/css">
      .container {
        width:960px;
        margin: auto;
        margin-top:100px;
      }

      body {
        font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
        font-weight: 300;
      }
    </style>
  </head>

  <body>
    <div class='container'>
      <% if logged_in_and_valid_user? %>
        <p align='center'><%= link_to 'Log out', sessions_path, method: :delete %></p>
      <% end %>
    </div>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/private/index.html.erb
<h1>Hello,</h1>

<h1>Welcome to our private space, only you can see this.</h1>

<h1>The developer</h1>

<h3>p.s. Is it really private?</h3>

app/views/users/new.html.erb
<h3>Welcome to our signup page</h3>

<%= form_for @user do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %> </p>

  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>

  <%= f.submit %>
<% end %>